### ISSUE TITLE
每次执行后，都会把保存的数据库的连接记录清空了，这个有办法么？

### ISSUE THREAD

**Issue by ChenRuihua** [Abeautifulsnow/navicat-premium-crack#2]
![Dingtalk_20201214120154](https://user-images.githubusercontent.com/46486133/102039277-4a2a2780-3e04-11eb-96ec-aa28e3172535.jpg)

如图，每次zh执行后，保存的数据库连接信息就都没了。这样不方便。有办法么？

谢谢。

**Comment by Abeautifulsnow** [comment]
抱歉，暂时还没有方法哈，您先平时备份一下连接信息。我后面再捣鼓捣鼓【我自用mac，在公司用的windows，所以能用windows的时候都在忙着别的事情😅】。。。

**Comment by Abeautifulsnow** [comment]
我更新了一下，貌似可以保留连接信息了。你可以试试看😑

**Comment by ChenRuihua** [comment]
谢谢，mac下有好办法解决么。我平时也是mac win换着用。

**Comment by Abeautifulsnow** [comment]
> 谢谢，mac下有好办法解决么。我平时也是mac win换着用。

不好意思哈。。。我自用的是pj版的。。。你可以自己找找看哈。。。这个问题应该解决掉了。。。我关掉问题了哈。。。
