### ISSUE TITLE
16.2.2 删注册表好像不行了

### ISSUE THREAD

**Issue by ghost** [Abeautifulsnow/navicat-premium-crack#3]
16.2.2 删注册表好像不行了

**Comment by Abeautifulsnow** [comment]
是吗？我用的还是旧版的。我有时间看看👀。

**Comment by notfound945** [comment]
没错 16.2.2 不行了

**Comment by Abeautifulsnow** [comment]
分支切换到v16，里面有个 `v16.bat` ，我已在本机测验16.2.5版本，可以重置日期。 @notfound945 @saodis

**Comment by notfound945** [comment]
👍 好的，我16.2.2已经重置了，现在就升级16.2.5

**Comment by ghost** [comment]
@Abeautifulsnow 有个疑问，运行 bat 后，桌面生成一个文件夹，有点奇怪。
![image](https://github.com/Abeautifulsnow/navicat-premium-crack/assets/51149477/3973da72-d13b-4a44-9443-2437976e10b0)

文件夹打不开，也删不掉

**Comment by Abeautifulsnow** [comment]
> @Abeautifulsnow 有个疑问，运行 bat 后，桌面生成一个文件夹，有点奇怪。 ![image](https://user-images.githubusercontent.com/51149477/256129435-3973da72-d13b-4a44-9443-2437976e10b0.png)
> 
> 文件夹打不开，也删不掉

你不说我还没发现，我也不知道😅怎么出现的。等后面找到办法了再说

**Comment by Abeautifulsnow** [comment]
@saodis 有法子了。我的已经通过下面这个办法删掉了。

```text
windows桌面出现无名空白文件，右键删除文件夹，再次刷新桌面还是会出现该文件夹。
解决办法：
1、右键该文件夹剪切到其他文件夹中，这时候会报错，将报错信息（一串字符串）记下来，例如：{138508BC-1E03-49EA-9C8F-EA9E1 D05D65D}，这是一个注册表里面得key信息。
2、然后键盘操作win+R，输入regedit，这时候你肯定找不到这个注册表key，所以要通过查找功能去查询上面那串字符串(不带花括号)，这期间可能会花费一些时间，耐心等待。。。等查询定位到这个key后，手动将这个key完全删除，然后继续查找，直到查找不到。(这同一个key可能在不同的注册表子项里面，所以需要一直查找)
```

**Comment by ghost** [comment]
> @saodis 有法子了。我的已经通过下面这个办法删掉了。
> 
> ```
> windows桌面出现无名空白文件，右键删除文件夹，再次刷新桌面还是会出现该文件夹。
> 解决办法：
> 1、右键该文件夹剪切到其他文件夹中，这时候会报错，将报错信息（一串字符串）记下来，例如：{138508BC-1E03-49EA-9C8F-EA9E1 D05D65D}，这是一个注册表里面得key信息。
> 2、然后键盘操作win+R，输入regedit，这时候你肯定找不到这个注册表key，所以要通过查找功能去查询上面那串字符串(不带花括号)，这期间可能会花费一些时间，耐心等待。。。等查询定位到这个key后，手动将这个key完全删除，然后继续查找，直到查找不到。(这同一个key可能在不同的注册表子项里面，所以需要一直查找)
> ```

你不说，我都忘记了，看了下，桌面文件夹没了😂

**Comment by ghost** [comment]
@Abeautifulsnow 试了一下，把 `echo Delete: %%a` 删了，跑了几次，桌面没发现有生成文件夹。
